STICKERS = {
    'st200': 'CAACAgIAAxkBAAPbXsQYJTuxd3KN0tC1qcYa3er0g5MAAiwBAAKmREgLNSbn5CwkdcMZBA',
    'st300': [
        'CAACAgIAAxkBAAPcXsQYR3Tk_xpW7QRUpF41nDl5AgoAAnEBAAKmREgLtkY4G2WhhxEZBA',
        'CAACAgIAAxkBAAPdXsQYXXhan-siITi90VsPCp3FvooAAiQBAAKmREgLC-fxc-_4BpAZBA'
    ],
    'st500': [
        'CAACAgIAAxkBAAPeXsQYcIhgrgzO8oW88VssjAdOIlMAAksEAALSWogBV6epQaXKjhMZBA',
        'CAACAgIAAxkBAAPfXsQYgbNyfKa1Ep28XVqk9AZ7GAkAAkUEAALSWogBIrPKdeG_ijMZBA'
    ],
    'st600': [
        'CAACAgIAAxkBAAPgXsQYkxJ1gX_apHL6SqRRO8qGiDsAAjgBAAKmREgLzFq81YtW_ukZBA',
        'CAACAgIAAxkBAAPhXsQYrM152GyasGnmir7RgL4XW_MAAnUBAAKmREgLNXjW57p3vNkZBA'
    ],
    'st700': 'CAACAgIAAxkBAAPiXsQYzq3NvSrK-i1y59FvTRCVMGoAAmkBAAKmREgLf93cTLwN7wkZBA',
    'st751': 'CAACAgIAAxkBAAPjXsQY4VRuvhsvfON-zv5NySCOq_4AAigBAAKmREgL1z6OME64E_4ZBA',
    'st762': 'CAACAgIAAxkBAAPkXsQY9H6ud70gSI1QvORh0g9PeOUAAjYBAAKmREgLC4izjG0lEKgZBA',
    '80001d': 'CAACAgIAAxkBAAPlXsQZBakvvky09WEom7BETszcN3AAAgIEAALSWogBAignTa7rtTEZBA',
    '80001n': 'CAACAgIAAxkBAAPmXsQZFjQW9ZLg98xukGAgHE3CIdMAAu4DAALSWogBIvF0dV77l0kZBA',
    '02d': 'CAACAgIAAxkBAAPnXsQZLEPjnoeFVPI1X-eK4esyaCEAAiIBAAKmREgLEfW5zI8V9GYZBA',
    '02n': 'CAACAgIAAxkBAAPoXsQZPeCM5TgDe71UQURFkjpap_oAAk8BAAKmREgLQ3xzRo3SQkEZBA',
    '03d': 'CAACAgIAAxkBAAPpXsQZUYdZsLWamB9ACKK77eN15mEAAiQEAALSWogBhgO0w66z4K8ZBA',
    '03n': 'CAACAgIAAxkBAAPqXsQZYhWKFHcrJ3MZCSUX8fqP4OgAAhoEAALSWogBWSS6bYplePMZBA',
    '04': 'CAACAgIAAxkBAAPrXsQZemAP4qqBj7idxbKJVp_aoFMAAjABAAKmREgLEXLvQtnLgB0ZBA',
    'sunset': 'CAACAgIAAxkBAAPsXsQZjh0w8fwcqPPWdbF5NOQw2KUAAuwDAALSWogBnTOfL3hinigZBA',
    'sunrise': 'CAACAgIAAxkBAAPtXsQZtQZFbhVdAT2i6rt13HPIx4MAAiABAAKmREgLiILXopXVHj4ZBA',
    'very_hot': [
        'CAACAgIAAxkBAAPuXsQZ1CESxjvCqSh0dHXscZ8aGv8AAwQAAtJaiAFy-kxfU-wkbxkE',
        'CAACAgIAAxkBAAPvXsQZ4rgc3TDrjc0DQuqKxp2GhuoAAhwEAALSWogBTFX-AAGd_0zSGQQ'
    ],
    'normalday': 'CAACAgIAAxkBAAPwXsQZ98QqLWIUzPVvFMiBjWiuBDYAAv4DAALSWogBUYxbzQbDucgZBA',
    'normalnight': 'CAACAgIAAxkBAAPxXsQaIDF21gkGJSnEI407q6oi9AgAAlsBAAKmREgLl3-VQqiCt70ZBA',
    'cold': 'CAACAgIAAxkBAAPyXsQaNznsDBtiwAdiCL2cBiDtKHcAAgkBAAJWnb0K1mZcg9c_qB0ZBA',
    'notsoday': 'CAACAgIAAxkBAAPzXsQaUWdytN5aaS-u0RDoT6wlxJIAAgIEAALSWogBAignTa7rtTEZBA',
    'notsonight': 'CAACAgIAAxkBAAP0XsQaYo-vwAABEtbAu2K8Ks34wsOhAALYBAAC0lqIARZNHWoFOj3AGQQ',
    'wind5': 'CAACAgIAAxkBAAP1XsQaeeYvO7k4fcHv9LEsvm48WbEAAiIEAALSWogBY3Ngm0AVYNwZBA',
    'wind4': 'CAACAgIAAxkBAAP2XsQajP6WvnRouQABXtx5jOQ2ZZZnAAJ3AQACpkRIC8AYuh5EKVJfGQQ'
}